// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emgsdptbhoupocvvpogl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZ3NkcHRiaG91cG9jdnZwb2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzYyNjcsImV4cCI6MjA2NjQ1MjI2N30.VCqXbSuZZcYhY8TCp6DkHavEX_lEjSK8g4d63E0_MJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);